In [1]:
import torch
from torch.utils import data
import numpy

In [13]:
x = torch.tensor(range(1,51))

In [14]:
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [16]:
y = torch.normal(mean=torch.arange(1., 51.), std=torch.arange(1, 0, -0.02))

In [17]:
y.reshape(-1,1)

tensor([[ 0.8342],
        [ 1.8010],
        [ 2.7628],
        [ 2.3609],
        [ 4.4612],
        [ 6.5179],
        [ 5.8828],
        [ 8.1877],
        [10.4607],
        [ 9.0983],
        [10.8335],
        [10.2430],
        [13.7366],
        [13.0059],
        [15.1466],
        [15.9450],
        [17.1402],
        [17.9228],
        [18.2525],
        [19.8906],
        [20.0821],
        [22.8677],
        [22.4945],
        [24.4458],
        [25.5376],
        [25.1024],
        [27.3246],
        [27.8676],
        [28.6217],
        [30.0895],
        [30.9877],
        [32.2737],
        [33.2966],
        [34.2918],
        [34.9822],
        [36.3678],
        [37.1080],
        [37.8488],
        [39.1045],
        [39.7011],
        [41.4390],
        [41.8650],
        [43.0137],
        [43.8970],
        [44.8647],
        [45.8754],
        [46.9765],
        [48.0550],
        [48.9922],
        [50.0006]])

In [18]:
x.reshape(-1,1)

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30],
        [31],
        [32],
        [33],
        [34],
        [35],
        [36],
        [37],
        [38],
        [39],
        [40],
        [41],
        [42],
        [43],
        [44],
        [45],
        [46],
        [47],
        [48],
        [49],
        [50]])

In [19]:
torch.utils.data.TensorDataset(x,y)

In [20]:
dataset = torch.utils.data.TensorDataset(x,y)

In [22]:
z=torch.utils.data.DataLoader(dataset,10,shuffle=True)

In [24]:
next(iter(z))

[tensor([39, 45, 35, 42, 20, 31, 50, 40, 32,  3]),
 tensor([39.1045, 44.8647, 34.9822, 41.8650, 19.8906, 30.9877, 50.0006, 39.7011,
         32.2737,  2.7628])]