In [1]:
import torch
from torch.utils import data
import numpy

In [13]:
x = torch.tensor(range(1,51))

In [14]:
x

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [16]:
y = torch.normal(mean=torch.arange(1., 51.), std=torch.arange(1, 0, -0.02))

In [17]:
y.reshape(-1,1)

tensor([[ 0.8342],
        [ 1.8010],
        [ 2.7628],
        [ 2.3609],
        [ 4.4612],
        [ 6.5179],
        [ 5.8828],
        [ 8.1877],
        [10.4607],
        [ 9.0983],
        [10.8335],
        [10.2430],
        [13.7366],
        [13.0059],
        [15.1466],
        [15.9450],
        [17.1402],
        [17.9228],
        [18.2525],
        [19.8906],
        [20.0821],
        [22.8677],
        [22.4945],
        [24.4458],
        [25.5376],
        [25.1024],
        [27.3246],
        [27.8676],
        [28.6217],
        [30.0895],
        [30.9877],
        [32.2737],
        [33.2966],
        [34.2918],
        [34.9822],
        [36.3678],
        [37.1080],
        [37.8488],
        [39.1045],
        [39.7011],
        [41.4390],
        [41.8650],
        [43.0137],
        [43.8970],
        [44.8647],
        [45.8754],
        [46.9765],
        [48.0550],
        [48.9922],
        [50.0006]])

In [18]:
x.reshape(-1,1)

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30],
        [31],
        [32],
        [33],
        [34],
        [35],
        [36],
        [37],
        [38],
        [39],
        [40],
        [41],
        [42],
        [43],
        [44],
        [45],
        [46],
        [47],
        [48],
        [49],
        [50]])

In [19]:
torch.utils.data.TensorDataset(x,y)

In [20]:
dataset = torch.utils.data.TensorDataset(x,y)

In [22]:
z=torch.utils.data.DataLoader(dataset,10,shuffle=True)

In [24]:
next(iter(z))

[tensor([39, 45, 35, 42, 20, 31, 50, 40, 32,  3]),
 tensor([39.1045, 44.8647, 34.9822, 41.8650, 19.8906, 30.9877, 50.0006, 39.7011,
         32.2737,  2.7628])]

## 20240416

In [1]:
from torch.utils.data import DataLoader, Dataset

# 自定义 Dataset 类
class MyDataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        return self.data[index]

# 创建数据集实例
data = [1, 2, 3, 4, 5]
dataset = MyDataset(data)

# 创建 DataLoader 实例
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

# 使用 DataLoader 迭代数据
for batch in dataloader:
    print(batch)

tensor([5, 1])
tensor([4, 2])
tensor([3])


In [2]:
try:
    raise ValueError("原始异常")
except ValueError as e:
    print("处理原始异常")
    raise TypeError("新异常") from e

处理原始异常


TypeError: 新异常

In [3]:
import torch
import torch.nn as nn
import torch.optim as optim

# 创建一个简单的神经网络模型和优化器
model = nn.Linear(1, 1)
optimizer = optim.SGD(model.parameters(), lr=0.01)

# 获取模型和优化器的状态字典
model_state_dict = model.state_dict()
optimizer_state_dict = optimizer.state_dict()

print("Model State Dict:")
print(model_state_dict)

print("\nOptimizer State Dict:")
print(optimizer_state_dict)

Model State Dict:
OrderedDict([('weight', tensor([[0.2824]])), ('bias', tensor([0.2067]))])

Optimizer State Dict:
{'state': {}, 'param_groups': [{'lr': 0.01, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'params': [0, 1]}]}


In [4]:
import pandas as pd

# 创建一个 DataFrame
data = {'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7,  8, 9]}
df = pd.DataFrame(data)

# 删除列
df_drop_col = df.drop(columns=['A', 'C'])

# 删除行
df_drop_row = df.drop(index=[0, 2])

print("Original DataFrame:")
print(df)

print("\nDataFrame after dropping column:")
print(df_drop_col)

print("\nDataFrame after dropping row:")
print(df_drop_row)

Original DataFrame:
   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

DataFrame after dropping column:
   B
0  4
1  5
2  6

DataFrame after dropping row:
   A  B  C
1  2  5  8


## iterator

In [5]:
class MyIterator:
    def __init__(self, max_num):
        self.max_num = max_num
        self.current_num = 0

    def __iter__(self):
        return self

    def __next__(self):
        if self.current_num < self.max_num:
            self.current_num += 1
            return self.current_num
        else:
            raise StopIteration

# 使用迭代器对象
my_iter = MyIterator(5)
for num in my_iter:
    print(num)

1
2
3
4
5
