# 20240417

## .1 eq()比大小

In [1]:
import torch

tensor1 = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
tensor2 = torch.tensor([[1, 0, 3],
                        [4, 5, 6]])
result = tensor1.eq(tensor2)
print(result)

tensor([[ True, False,  True],
        [ True,  True,  True]])


In [4]:
import torch

tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
scalar = 3
result = tensor.eq(scalar)
print(result)

tensor([[False, False,  True],
        [False, False, False]])


## 2 torch.max()

### 整个张量最大

In [5]:
import torch

tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
max_value = torch.max(tensor)
print(max_value)  # 输出 6

tensor(6)


### 沿某个维度最大

In [7]:
import torch

tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
# 沿着第一个维度（行）找到最大值
max_values, _ = torch.max(tensor, dim=1)
print(max_values)  # 输出 tensor([3, 6])

tensor([3, 6])


## 3 .view_as()

In [9]:
import torch

# 创建一个大小为 (2, 3) 的张量
tensor = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])

# 创建一个与上面张量形状相同的目标张量
target_tensor = torch.zeros_like(tensor)

# 创建一个目标张量
target_tensor1 = torch.zeros(3,2)


# 使用 view_as() 方法将其重塑为目标张量的形状
reshaped_tensor = tensor.view_as(target_tensor1)

print("原始张量形状:", tensor.shape)
print("目标张量形状:", target_tensor1.shape)
print("重塑后张量形状:", reshaped_tensor.shape)

原始张量形状: torch.Size([2, 3])
目标张量形状: torch.Size([3, 2])
重塑后张量形状: torch.Size([3, 2])
